### ISSUE TITLE
Does not support PostgreSQL array and json

### ISSUE THREAD

**Issue by mudlee** [shinichi-takii/ddlparse#25]
The parsing silently fails, if any of those two field types is present in the PostgreSQL schema:
- character varying[]
- json

**Comment by shinichi-takii** [comment]
@mudlee 
Thank you for the report.
I fixed issue to v1.2.1.

**Comment by mudlee** [comment]
Hi, I have to reopen it, it almost good, but it does not support default values, it will silent fail again. Removing default values solves the problem ofc.
Example field:
`my_field character varying[] DEFAULT '{}'::character varying[],`

**Comment by mudlee** [comment]
Oh, I cant reopen it... then please take a look at it. 
Thank you for your awesome work btw! The best and only stuff that works.

**Comment by mudlee** [comment]
Also, I get a warning message too:
`/usr/local/lib/python3.7/site-packages/pyparsing.py:2910: FutureWarning: Possible nested set at position 1
  self.re = re.compile( self.reString )`

**Comment by shinichi-takii** [comment]
`FutureWarning` has created a new issue to #29.

**Comment by shinichi-takii** [comment]
@mudlee
Thank you for reporting again.
I fixed issue to v1.2.2.
