### ISSUE TITLE
Parse error for MySQL DDL with comma in COMMENT string

### ISSUE THREAD

**Issue by frozenpine** [shinichi-takii/ddlparse#41]
if a comma in column's comment string, parse result will discard all other columns behind it.

![image](https://user-images.githubusercontent.com/19898918/62934113-61af6580-bdf6-11e9-8a71-1ba95d0fa625.png)

all columns behind `direction` will be discarded.

**Comment by aiphee** [comment]
This issue also affects me, can we please try to resolve it?

**Comment by shinichi-takii** [comment]
@frozenpine @aiphee 
Thank you for reporting.

I fixed this issue.
Please upgrade the package to `v1.5.0`.

```
$ pip --no-cache-dir install --upgrade ddlparse
```

Thanks
