### ISSUE TITLE
Support Oracle's `TIMESTAMP(fractional_seconds_precision)` data type

### ISSUE THREAD

**Issue by chikfm** [shinichi-takii/ddlparse#6]
# Requirements
- Support Oracle's `TIMESTAMP(fractional_seconds_precision)` data type. 
  - The valid range of _fractional_seconds_precision_ is 0 to 9.
  - BigQuery Supported  seconds_precision is 0 to 6 both Legacy and Standard.

# Links
- Oracle Document
  - http://otndnld.oracle.co.jp/document/products/oracle11g/111/doc_dvd/server.111/E05750-03/sql_elements.htm#26587
- BigQuery Document
  - Legacy: https://cloud.google.com/bigquery/data-types?hl=ja
  - Standard: https://cloud.google.com/bigquery/sql-reference/data-types?hl=ja

**Comment by shinichi-takii** [comment]
### Japanese
`ddlparse` として何が問題なのか分かりませんでした。
Oracle 'TIMESTAMP(n)' は BigQuery 'DATETIME' に変換できています。
7桁以上の精度がBigQueryで保持できないことは、 `ddlparse` の動作に影響を与えるべき課題ではないと思います。

### English (Google Translation)
I did not know what is wrong as `ddlparse`.
Oracle 'TIMESTAMP (n)' has been converted to BigQuery 'DATETIME'.
I think that it is not a problem to affect the operation of `ddlparse` that BigQuery can not hold precision of more than 7 digits.

**Comment by chikfm** [comment]
issueの記載がよくありませんでした。
OracleのDDLとして `TIMESTAMP(6)` というカラム定義があったときにエラーになってしまう、という事象です。
おそらく `TIMESTAMP(p)` という記載が想定されていないことが原因ではないかと思われます。
- サンプルコード
```
# -*- coding: utf-8 -*-
from ddlparse import DdlParseTable
import json
from pprint import pprint

_table = DdlParseTable()

IDX_COLUMN_NAME = 0
IDX_DATA_TYPE = 1
IDX_DATA_LENGTH = 2
IDX_DATA_PRECISION = 3
IDX_DATA_SCALE = 4
IDX_NULLABLE = 5

read_str="""
SITE_UPDATE_TIME,TIMESTAMP(6),11,,6,Y
"""

for line in read_str.replace("\t", ",").split("\n"):
    if len(line) == 0:
        continue

    fields = line.split(',')

    if fields[IDX_DATA_LENGTH] != "":
        if fields[IDX_DATA_SCALE] == "":
            opt = "({})".format(fields[IDX_DATA_LENGTH])
        else:
            opt = "({},{})".format(fields[IDX_DATA_LENGTH],
                                   fields[IDX_DATA_SCALE])

        arr = [fields[IDX_DATA_TYPE], opt]
    else:
        arr = [fields[IDX_DATA_TYPE]]

    _table.columns.append(column_name=fields[IDX_COLUMN_NAME],
                               data_type_array=arr
                               ).not_null = True \
        if fields[IDX_NULLABLE] == 'N' else False

ret = json.loads(_table.to_bigquery_fields())

pprint(ret)
```
- エラーメッセージ
```
Traceback (most recent call last):
  File "<string>", line 77, in <module>
  File "$HOME/anaconda3/lib/python3.6/site-packages/ddlparse/ddlparse.py", line 252, in to_bigquery_fields
    bq_fields.append(col.to_bigquery_field(name_case))
  File "$HOME/anaconda3/lib/python3.6/site-packages/ddlparse/ddlparse.py", line 188, in to_bigquery_field
    return '{{"name": "{}", "type": "{}", "mode": "{}"}}'.format(self._get_name(name_case), self.bigquery_data_type, self.bigquery_mode)
  File "$HOME/anaconda3/lib/python3.6/site-packages/ddlparse/ddlparse.py", line 177, in bigquery_data_type
    raise ValueError("Unknown data type : '{}'".format(self._data_type))
ValueError: Unknown data type : 'TIMESTAMP(6)'
```

**Comment by chikfm** [comment]
- Oracleの`DBA_TAB_COLUMNS`テーブルより`DATA_TYPE`を取得すると、`TIMESTAMP`型の場合`TIMESTAMP(6)`が取得されます
- DDL（`create ...`）ではなく`DBA_TAB_COLUMNS`の値を使ってパース処理を行おうとするとエラーになりました。
- 当方のパッケージの使用方法（`DdlParseTable().columns.append`へのパラメタの渡し方）に誤りがありましたので本件はクローズさせていただきます
