### ISSUE TITLE
Unknown data type VARBINARY

### ISSUE THREAD

**Issue by dkrysmann** [shinichi-takii/ddlparse#60]
Hi,
Thank you all for this great package.
While using it to parse DDL I have stumbled on error: ValueError: Unknown data type : 'VARBINARY

Is this a bug or I'm missing something?

Regards,
Darek

**Comment by shinichi-takii** [comment]
@dkrysmann 
Thank you for reporting.

I fixed this issue.
Please upgrade the package to `v1.9.0`.

Thanks.
