### ISSUE TITLE
OracleのNCLOBに対応していない

### ISSUE THREAD

**Issue by chikfm** [shinichi-takii/ddlparse#9]
- `NCLOB` 型のカラムを変換しようとすると `Unknown data type : 'NCLOB'` となります。
- 参考
   - https://blogs.oracle.com/oracle4engineer/loblobblobclobsecurefiles

> ＜内部LOB （ Oracle Database内部に格納するLOB ）＞
>BLOB ： バイナリデータを格納
>CLOB ： 文字データを格納
>NCLOB ： 各国語キャラクタ・セットの文字データを格納
>＜外部LOB （ Oracle Database 表領域の外にあるOSファイルに格納 ）＞
>BFILE ： 読み取り専用（アプリケーション内で書込みできない）

**Comment by shinichi-takii** [comment]
fixed v1.1.2
